module.exports = {
  read: {
    "/dashboard": ["super_admin"],
    "/dashboard/users": ["super_admin"],
    "/dashboard/dwellings": ["super_admin", "user"],
    "/dashboard/dwellings/form": ["super_admin", "user"],
    "/dashboard/dwellings/form/*": ["super_admin", "user"],
    "/dashboard/dwellings/amenities": ["super_admin"],
    "/dashboard/dwellings/categories": ["super_admin"],
    "/dashboard/dwellings/equipments": ["super_admin"],
    "/dashboard/dwellings/galleries": ["super_admin"],
    "/dashboard/dwellings/guidelines": ["super_admin"],
    "/dashboard/statistics": ["super_admin", "user"],
    "/dashboard/blog": ["super_admin"],
    "/dashboard/blog/categories": ["super_admin"],
    "/dashboard/locations": ["super_admin"],
    "/dashboard/locations/countries": ["super_admin"],
    "/dashboard/packages": ["super_admin"],
    "/dashboard/subscriptions": ["super_admin"],
    "/dashboard/me": ["super_admin", "user"],
    "/dashboard/invoices": ["super_admin", "user"],
    "/dashboard/messenger": ["super_admin", "user"],
  },
  create: {
    "/dashboard/users": ["super_admin"],
    "/dashboard/dwellings": ["super_admin", "user"],
    "/dashboard/dwellings/amenities": ["super_admin"],
    "/dashboard/dwellings/categories": ["super_admin"],
    "/dashboard/dwellings/equipments": ["super_admin"],
    "/dashboard/dwellings/galleries": ["super_admin"],
    "/dashboard/blogs": ["super_admin"],
    "/dashboard/blogs/categories": ["super_admin"],
    "/dashboard/statistics": ["super_admin", "user"],

    "/dashboard/dwellings/guidelines": ["super_admin"],
    "/dashboard/locations": ["super_admin"],
    "/dashboard/locations/countries": ["super_admin"],
    "/dashboard/packages": ["super_admin"],
    "/dashboard/subscriptions": ["super_admin"],
    "/dashboard/me": ["super_admin", "user"],
    "/dashboard/invoices": ["super_admin", "user"],
    "/dashboard/messenger": ["super_admin", "user"],
  },
  update: {
    "/dashboard/users": ["super_admin"],
    "/dashboard/dwellings": ["super_admin", "user"],
    "/dashboard/dwellings/amenities": ["super_admin"],
    "/dashboard/dwellings/categories": ["super_admin"],
    "/dashboard/dwellings/equipments": ["super_admin"],
    "/dashboard/statistics": ["super_admin", "user"],

    "/dashboard/dwellings/galleries": ["super_admin"],
    "/dashboard/dwellings/blog": ["super_admin"],
    "/dashboard/dwellings/blog/categories": ["super_admin"],
    "/dashboard/dwellings/guidelines": ["super_admin"],
    "/dashboard/locations": ["super_admin"],
    "/dashboard/locations/countries": ["super_admin"],
    "/dashboard/packages": ["super_admin"],
    "/dashboard/subscriptions": ["super_admin"],
    "/dashboard/me": ["super_admin", "user"],
    "/dashboard/invoices": ["super_admin", "user"],
    "/dashboard/messenger": ["super_admin", "user"],
  },
  delete: {
    "/dashboard/users": ["super_admin"],
    "/dashboard/dwellings": ["super_admin", "user"],
    "/dashboard/dwellings/amenities": ["super_admin"],
    "/dashboard/dwellings/categories": ["super_admin"],
    "/dashboard/dwellings/equipments": ["super_admin"],
    "/dashboard/blogs": ["super_admin"],
    "/dashboard/blogs/categories": ["super_admin"],
    "/dashboard/dwellings/galleries": ["super_admin"],
    "/dashboard/statistics": ["super_admin", "user"],

    "/dashboard/dwellings/guidelines": ["super_admin"],
    "/dashboard/locations": ["super_admin"],
    "/dashboard/locations/countries": ["super_admin"],
    "/dashboard/packages": ["super_admin"],
    "/dashboard/subscriptions": ["super_admin"],
    "/dashboard/me": ["super_admin", "user"],
    "/dashboard/invoices": ["super_admin", "user"],
    "/dashboard/messenger": ["super_admin", "user"],
  },
};
